title: "Why <br>we <br>measure <br>what,<br>how, <br>and <br>where"
author: Bilge Kobas
copyright: "2026, Bilge Kobas. Why We Measure What, How and Where. · CC BY 4.0"
only_build_toc_files: true

parse:
  myst_enable_extensions:
    - colon_fence
    - linkify

html:
  extra_css:
    - _static/custom.css

  extra_head: |
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

  extra_path:
    - assets

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - sphinxcontrib.mermaid
  config:
    html_static_path:
      - _static
    html_extra_path:
      - assets
    html_js_files:
      - glossary-search.js
    bibtex_bibfiles:
      - WhyWeMeasure_v04.bib
    bibtex_reference_style: author_year

